export const FETCH_LIST_REQUEST = 'list/FETCH_LIST_REQUEST';
export const FETCH_LIST_SUCCESS = 'list/FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAILURE = 'list/FETCH_LIST_FAILURE';

export const ADD_ELEMENT_REQUEST = 'list/ADD_ELEMENT_REQUEST';
export const ADD_ELEMENT_SUCCESS = 'list/ADD_ELEMENT_SUCCESS';
export const ADD_ELEMENT_FAILURE = 'list/ADD_ELEMENT_FAILURE';

export const EDIT_ELEMENT_REQUEST = 'list/EDIT_ELEMENT_REQUEST';
export const EDIT_ELEMENT_SUCCESS = 'list/EDIT_ELEMENT_SUCCESS';
export const EDIT_ELEMENT_FAILURE = 'list/EDIT_ELEMENT_FAILURE';

export const FETCH_ELEMENT_REQUEST = 'list/FETCH_ELEMENT_REQUEST';
export const FETCH_ELEMENT_SUCCESS = 'list/FETCH_ELEMENT_SUCCESS';
export const FETCH_ELEMENT_FAILURE = 'list/FETCH_ELEMENT_FAILURE';

export const DELETE_ELEMENT_REQUEST = 'list/DELETE_ELEMENT_REQUEST';
export const DELETE_ELEMENT_SUCCESS = 'list/DELETE_ELEMENT_SUCCESS';
export const DELETE_ELEMENT_FAILURE = 'list/DELETE_ELEMENT_FAILURE';