FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# tshchemistry

This is an example API to keep track of known elements and their properties

## Elements Collection [/elements]

### List All Elements [GET]

+ Response 200 (application/json)

    [
        {
            "id": 1,
            "name": "Hydrogen",
            "atomicWeight": 1,
            "atomicNumber": 1,
            "group": 1,
            "period": 1
            "finder": "Henry Cavendish ?"
        },
        {
            "id": 2,
            "name": "Helium",
            "atomicWeight": 4,
            "atomicNumber": 2,
            "group": 1,
            "period": 1
            "finder": "???"
        },
        {
            "id": 3,
            "name": "Lithium",
            "atomicWeight": 6,
            "atomicNumber": 3,
            "group": 1,
            "period": 2
            "finder": "???"
        }
    ]

### Create a New Element [POST]

If you have discovered new element, you can add it using this to periodic table

+ Request (application/json)

    {
        "name": "Beryllium",
        "atomicWeight": 9,
        "atomicNumber": 4,
        "group": 2,
        "period": 2,
        "finder": "Vauqelin?"
    }
    
+ Response 204 (application/json)

## Manage Elements [/elements/{id}]

+ Parameters
    + id: 1
 
### Fetch single Element [GET]

You just need a single element

+ Response 200 (application/json)

    {
        "name": "Beryllium",
        "atomicWeight": 9,
        "atomicNumber": 4,
        "group": 2,
        "period": 2,
        "finder": "Vauqelin?"
    }
    
### Edit an Element [PUT]

There is a mistake in a periodic table that needs to be fixed.

+ Request (application/json)

    {
        "name": "Beryllium",
        "atomicWeight": 9,
        "atomicNumber": 4,
        "group": 2,
        "period": 2,
        "finder": "Vauqelin?"
    }
    
+ Response 204 (application/json)

### Delete an Element [DELETE]

+ Response 204